/** Original imagery generated for Vivra. Dimensions are the source pixel sizes. */
export const IMG = {
  mosqueMinbar: { src: "/images/mosque-minbar.jpg", w: 896, h: 1120, alt: "Minbar with a microphone inside a light-filled contemporary mosque" },
  mosqueCongregation: { src: "/images/mosque-congregation.jpg", w: 1344, h: 752, alt: "Congregation seated in a contemporary mosque, seen from behind" },
  mosqueMicrophone: { src: "/images/mosque-microphone.jpg", w: 896, h: 1120, alt: "Slim microphone on a wooden lectern in a mosque" },
  mosqueListener: { src: "/images/mosque-listener.jpg", w: 896, h: 1120, alt: "A worshipper listening on a phone with one earphone, seen from behind" },
  mosqueExterior: { src: "/images/mosque-exterior.jpg", w: 1024, h: 688, alt: "Contemporary mosque exterior at golden hour with a reflecting pool" },
  eventsStage: { src: "/images/events-stage.jpg", w: 896, h: 1120, alt: "A speaker on a conference stage lit by a single beam of light" },
  eventsHall: { src: "/images/events-hall.jpg", w: 1344, h: 752, alt: "A large conference hall during an international summit" },
  eventsListener: { src: "/images/events-listener-translation.jpg", w: 896, h: 1120, alt: "An attendee holding a phone with an earphone in, stage lights behind" },
  eventsPanel: { src: "/images/events-panel.jpg", w: 896, h: 1120, alt: "A panel microphone on stage with speakers in the background" },
  eventsAuditorium: { src: "/images/events-auditorium.jpg", w: 1024, h: 688, alt: "An empty modern auditorium with teal architectural lighting" },
  techArchitecture: { src: "/images/tech-architecture.jpg", w: 1344, h: 752, alt: "White curved architecture with a soft violet light reflection" },
  stageMicrophone: { src: "/images/stage-microphone.jpg", w: 500, h: 750, alt: "A vintage chrome microphone under deep blue stage light" },
  eventsConfHall: { src: "/images/events-conf-hall.jpg", w: 1024, h: 688, alt: "A vast international conference hall with thousands of attendees facing a lit stage, graded in deep teal" },
  eventsConfCrowd: { src: "/images/events-conf-crowd.jpg", w: 1024, h: 1024, alt: "A conference audience applauding toward a bright stage, seen from behind, in teal light" },
  eventsConfListener: { src: "/images/events-conf-listener-translation.jpg", w: 1024, h: 1024, alt: "An attendee at a summit holding a phone with one earphone in, teal stage lights behind" },
  eventsModeModerator: { src: "/images/events-mode-moderator.jpg", w: 896, h: 1120, alt: "A conference sound desk with a laptop and glowing mixer faders in teal light" },
  eventsModeMultimic: { src: "/images/events-mode-multimic.jpg", w: 896, h: 1120, alt: "A panel table with an individual microphone at each seat, in teal light" },
  eventsModeVoiceId: { src: "/images/events-mode-voiceid.jpg", w: 896, h: 1120, alt: "A handheld microphone passed between hands during audience Q&A, in teal light" },
  mosqueHall: { src: "/images/mosque-hall.jpg", w: 1024, h: 688, alt: "Worshippers seated in a grand mosque prayer hall, seen from behind, in emerald light" },
  mosqueArches: { src: "/images/mosque-arches.jpg", w: 1024, h: 1024, alt: "A serene mosque interior with tall slender arches and green carpet" },
  mosquePhone: { src: "/images/mosque-phone.jpg", w: 1024, h: 1024, alt: "A worshipper listening on a phone with one earphone, seen from behind, in green light" },
  mosqueCourtyard: { src: "/images/mosque-courtyard.jpg", w: 1024, h: 688, alt: "A contemporary mosque courtyard in soft morning light" },
  mosqueMinbarDetail: { src: "/images/mosque-minbar-detail.jpg", w: 896, h: 1120, alt: "A wooden minbar and a slim microphone in emerald light" },
  mosqueHands: { src: "/images/mosque-hands.jpg", w: 896, h: 1120, alt: "Hands holding a phone on a knee in a prayer hall" },
  mosqueOffice: { src: "/images/mosque-office.jpg", w: 896, h: 1120, alt: "A laptop on a desk beside a pointed-arch window in a mosque office" },
  vSummit: { src: "/images/vivra-summit.jpg", w: 1024, h: 688, alt: "summit in soft violet light" },
  vArches: { src: "/images/vivra-arches.jpg", w: 1024, h: 1024, alt: "arches in soft violet light" },
  vPhoneHands: { src: "/images/vivra-phone-hands.jpg", w: 1024, h: 1024, alt: "phone hands in soft violet light" },
  vSoundDesk: { src: "/images/vivra-sounddesk.jpg", w: 1024, h: 688, alt: "sounddesk in soft violet light" },
  vAttendee: { src: "/images/vivra-attendee.jpg", w: 896, h: 1120, alt: "attendee in soft violet light" },
  vStage: { src: "/images/vivra-stage.jpg", w: 1024, h: 688, alt: "stage in soft violet light" },
  vPanel: { src: "/images/vivra-panel.jpg", w: 1024, h: 688, alt: "panel in soft violet light" },
  vBoardroom: { src: "/images/vivra-boardroom.jpg", w: 1024, h: 688, alt: "boardroom in soft violet light" },
  vMosqueHall: { src: "/images/vivra-mosque-hall.jpg", w: 1024, h: 688, alt: "mosque hall in soft violet light" },
  eventsCardGlass: { src: "/images/events-card-glass.jpg", w: 1024, h: 688, alt: "A translucent teal glass sculpture of flowing sound waves" },
  eventsCardSphere: { src: "/images/events-card-sphere.jpg", w: 1024, h: 1024, alt: "A glossy teal glass sphere with concentric ripples" },
  eventsCardRibbons: { src: "/images/events-card-ribbons.jpg", w: 1024, h: 1024, alt: "Pearlescent teal glass ribbons in soft light" },
  techRibbons: { src: "/images/tech-ribbons.jpg", w: 1344, h: 752, alt: "Translucent white ribbons with violet light flowing like sound" },
} as const;
